### ISSUE TITLE
Broken indentation on single-line if with comment

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/brighterscript-formatter#13]
I've noticed a bug where adding a comment after a single-line `if ... then ...` statement breaks indentation. The following code...

```brightscript
function a() as Integer

    b = 1

    if b = 6 ' this one is alright
        return 0
    end if

    if b = 1 then b = 2
    if b = 2 then b = 4 ' but this one breaks indentation
    if b = 4 then return 2

end function
```

...will result in this (`formatOnSave` is on):

![ezgif com-optimize](https://user-images.githubusercontent.com/57358121/81067257-4f221280-8ed6-11ea-94a5-e71de3d1f3e0.gif)

**Comment by TwitchBronBron** [comment]
Nice catch. The single-line-if statements have been a real pain in this formatter because we don't use a parser. However, I think we will need to use at least a subset of the parser to parse if statements. 

I'll try to carve out an hour or two so I can investigate whether the parser will work with this situation, or if there's another way to fix this. 

What has me concerned with a simple non-parser approach is this line in the code: 
![image](https://user-images.githubusercontent.com/2544493/81107816-be533300-8ee5-11ea-9ea5-f3e90732a65a.png)

Not really sure why I have that there...

**Comment by TwitchBronBron** [comment]
In order to accurately detect a single-line if statement compared to a multi-line, we need something smarter than the current formatter implementation (i.e. an actual parser). Luckily, as of [v1.1.0](https://github.com/rokucommunity/brighterscript-formatter/blob/master/CHANGELOG.md#110---2020-04-23) which was released on 4/23/2020, we do have a parser available within the formatter. I don't want to use a parser for all formatting because it's slower, less flexible, and more prone to fail for not-yet-supported syntax. 

So, here's my current thought: 
If we detect an `if` token, then we:
1. feed all of the tokens for the current line into the parser and _only_ parse that line. 
1. if there are no errors detected, and we get back an `IfStatement` object from the parser, that means it parsed properly, which should suffice for a `isSingleLineIfStatement()` check. 

I've been turning this around in my head for a while now trying to work out the kinks. I'll try and devote some time to this issue in the next week or two and see how it goes. 

Feel free to keep bugging me about this until you get what you want. 😃

**Comment by georgejecook** [comment]
I was about to report this as it makes rooibos code go crazy - I don't like this style anyhow, so I'm updating my code :)

**Comment by TwitchBronBron** [comment]
Well, my initial plan of only parsing a single line won't work. Take a look at this "single-line" if statement: 

```
if true content.Push({
    someProp: true
})
```

I'll need to come up with a better way in the parser to stop parsing after it finds the first if statement. There might need to be some type of event system in the parser that notifies us when we find something, and allow us to tell the parser to stop. 

Not a blocker, just more to think about. And honestly, we could probably go with my original approach for now, and enhance later.
